<?php

namespace AppBundle\Repository;

/**
 * DavidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DavidRepository extends \Doctrine\ORM\EntityRepository
{
}
